@startuml

App -- I_O
I_O -- Control
I_O -- Authentication
Authentication- Control
Control -- AdminsController
Control -- PlayersController
Control -- TeamsController
Control -- TournamentsController
TournamentsController -- Tournament
Tournament -- MatchmakingController
MatchmakingController -- Matchmaking
AdminsController -- Admin
PlayersController -- Player
Player -- Stat
Stat -- Categories
TeamsController -- Team
Player - Team
Participant - Tournament
Tournament - Date
Tournament -- Categories


class App{
}

class User{
}

class Player extends User implements Participant{
}

class Admin extends User{
}

class Categories{
}

class Stat{
}

class Team implements Participant{
}

class Matchmaking{
}

class Tournament{
}

class AdminsController{
}

class PlayersController{
}

class Authentication{
}

class TournamentsController{
}

class TeamsController{
}

interface Participant{
}

class ModelException{
}

class Control{
}

class Date{
}

class I_O{
}

class MatchmakingController{
}

class Validations{
}

@enduml